; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:a-star32U4]
platform = atmelavr
board = a-star32U4
framework = arduino
lib_deps = pololu/Pololu3piPlus32U4@^1.1.3
build_flags = -std=c++17
build_src_filter = +<**/*> -<main_trainer.cc> -<main-pr.cc>

[env:newthing]
platform = atmelavr
board = a-star32U4
framework = arduino
lib_deps = pololu/Pololu3piPlus32U4@^1.1.3
build_flags = -std=c++17
build_src_filter = +<main-pr.cc>

[env:trainer]
platform = atmelavr
board = a-star32U4
framework = arduino
lib_deps = pololu/Pololu3piPlus32U4@^1.1.3
build_flags = -std=c++17
build_src_filter =
    +<robot/subsystems/line_follower/line_follower.cc>
    +<robot/subsystems/line_follower/pid_trainer.cc>
    +<main_trainer.cc>
